name: CS2 Cheat MSBuild

on:
  workflow_dispatch:
  push:

env:
  SOLUTION_FILE_PATH: CS2CheatCpp.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild -version    
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="x64" -t:rebuild -verbosity:diag ${{env.SOLUTION_FILE_PATH}}

    - name: Show MSBuild Cpp Output
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: | 
         cd build
         dir
      shell: cmd
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
         name: cs2-cheat
         path: build/CS2CheatCpp.exe
