name: CS2 Cheat MSBuild

on:
  workflow_dispatch:
  push:

env:
  SOLUTION_FILE_PATH: CS2CheatCpp.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild -version    
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="x64" -t:rebuild -verbosity:diag ${{env.SOLUTION_FILE_PATH}}

    - name: Show MSBuild Cpp Output
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run:  | 
         cd build
         dir
      shell: cmd

    - name: Commit and Push Build Artifacts
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add ./build/CS2CheatCpp.exe
        git commit -m "Add built artifact for CS2 Cheat"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
